name: Conventional Versioning
description: GitHub Action that returns a semantic version based on Conventional Commits
branding:
  icon: tag
  color: blue

inputs:
  github-token:
    description: GitHub token
    default: ${{ github.token }}
  default-bump:
    description: Default version bump (major, minor, or patch)
    default: patch
  ignore-prereleases:
    description: Ignore prereleases when calculating the next version (true or false)
    default: false
  ignore-drafts:
    description: Ignore draft releases when calculating the next version (true or false)
    default: false
  mode:
    description: Sets the version mode to run - future use-case
    default: default

outputs:
  version:
    description: Semantic version without prefix
  version-with-prefix:
    description: Semantic version with prefix
  previous-version:
    description: Previous version used for the bump without prefix
  previous-version-with-prefix:
    description: Previous version used for the bump with prefix
  major:
    description: Major version number
  major-with-prefix:
    description: Major version number with prefix
  minor:
    description: Minor version number
  patch:
    description: Patch version number

runs:
  using: "node20"
  main: "dist/index.js"
